app:
  env: 'local'
  port: 8888
  app_name: 'colatiger'
  app_url: 'http://localhost'

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800




database:
  driver: 'mysql'
  host: '127.0.0.1'
  port: 3308
  database: 'cola_tiger'
  table_prefix: ''
  username: 'root'
  password: 'Abcd1234'
  charset: 'utf8mb4'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: 'info'
  enable_file_log_writer: true
  log_filename: 'sql.log'


redis:
  host: '127.0.0.1'
  port: 6379
  db: 0
  password: ''


log:
  level: 'info'
  root_dir: 'storage/logs'
  filename: 'app.log'
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true
