app:
  env: 'prod'
  port: 8000
  app_name: 'caixun'
  app_url: '0.0.0.0'

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800

database:
  driver: 'mysql'
  host: '192.168.87.185'
  port: 3306
  database: 'caixun'
  table_prefix: ''
  username: 'thundersoft'
  password: 'thundersoft'
  charset: 'utf8mb4'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: 'debug'
  enable_file_log_writer: true
  log_filename: 'sql.log'
  create_table: true

redis:
  host: '192.168.87.185'
  port: 6379
  db: 6
  password: '123456'

oss:
  endpoint: '192.168.87.185:9000'
  access_key: 'thundersoft'
  secret_access_key: 'thundersoft'
  bucket_name: 'poc'
  use_ssl: false


milvus:
  server: 192.168.87.216:19530

log:
  level: 'info'
  root_dir: 'storage/logs'
  filename: 'app.log'
  max_backups: 3
  max_size: 500
  max_age: 1
  compress: true
  show_line: true
  log_in_console: true
