env: local
http:
  host: 0.0.0.0
  port: 8000

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800

data:
  mysql: root:Abcd1234@tcp(127.0.0.1:3308)/cola_tiger?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s


minio:
  endpoint: 127.0.0.1:9000
  accessKeyID: colatiger
  secretAccessKey: colatiger


log:
  level: 'info'
  root_dir: 'storage/logs'
  filename: 'app.log'
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true
